import type { Metadata } from 'next';
import { redirect } from 'next/navigation';

import { PublicPortfolio } from '@/features/portfolio/components/PublicPortfolio';
import type { PublicPortfolioData } from '@/features/portfolio/types/portfolio.types';
import type { ApiResponse } from '@/lib/api/api.types';

interface PortfolioPublicPageProps {
    params: Promise<{ username: string }>;
}

const API_BASE =
    process.env.NEXT_PUBLIC_API_BASE_URL || 'http://localhost:4000/api/v1';

interface FetchResult {
    data: PublicPortfolioData | null;
    redirectTo: string | null;
}

async function fetchPortfolio(username: string): Promise<FetchResult> {
    try {
        const res = await fetch(`${API_BASE}/portfolio/public/${username}`, {
            next: { revalidate: 60 },
            redirect: 'manual',
        });

        const json = (await res.json()) as ApiResponse<PublicPortfolioData & { redirect?: string }>;

        // Handle username redirect (old username → new username)
        if (json.data?.redirect) {
            return { data: null, redirectTo: json.data.redirect };
        }

        if (!res.ok) return { data: null, redirectTo: null };
        return { data: json.data, redirectTo: null };
    } catch {
        return { data: null, redirectTo: null };
    }
}


export async function generateMetadata({ params }: PortfolioPublicPageProps): Promise<Metadata> {
    const { username } = await params;
    const { data: portfolio, redirectTo } = await fetchPortfolio(username);

    if (redirectTo || !portfolio) {
        return { title: 'Specialist' };
    }

    const title = portfolio.displayName;
    const description = [
        portfolio.niche,
        portfolio.city,
        portfolio.averageRating > 0
            ? `★ ${portfolio.averageRating.toFixed(1)} (${portfolio.reviewsCount})`
            : null,
        portfolio.services.length > 0
            ? `${portfolio.services.length} სერვისი`
            : null,
    ]
        .filter(Boolean)
        .join(' · ') || 'სილამაზის სპეციალისტი Glow.GE-ზე';

    return {
        title,
        description,
        openGraph: {
            type: 'profile',
            title: `${title} | Glow.GE`,
            description,
            url: `https://glow.ge/specialist/${username}`,
            // images are auto-generated by opengraph-image.tsx
        },
        twitter: {
            card: 'summary_large_image',
            title: `${title} | Glow.GE`,
            description,
        },
    };
}

export default async function PortfolioPublicPage({ params }: PortfolioPublicPageProps): Promise<React.ReactElement> {
    const { username } = await params;

    // Check for username redirect before rendering
    const { redirectTo } = await fetchPortfolio(username);
    if (redirectTo) {
        redirect(`/specialist/${redirectTo}`);
    }

    return <PublicPortfolio username={username} />;
}
