export const API_ENDPOINTS = {
    AUTH: {
        REGISTER: '/auth/register',
        LOGIN: '/auth/login',
        LOGOUT: '/auth/logout',
        REFRESH: '/auth/refresh',
        ME: '/auth/me',
        VERIFY_EMAIL: '/auth/verify-email',
        REQUEST_PASSWORD_RESET: '/auth/request-password-reset',
        RESET_PASSWORD: '/auth/reset-password',
        CHANGE_PASSWORD: '/auth/change-password',
        CHANGE_PASSWORD_REQUEST_OTP: '/auth/change-password/request-otp',
        VERIFY_PHONE: '/auth/verify-phone',
        RESEND_OTP: '/auth/resend-otp',
        GOOGLE: '/auth/google',
        SET_PHONE: '/auth/set-phone',
        RECOVER_PASSWORD_REQUEST: '/auth/recover-password/request',
        RECOVER_PASSWORD: '/auth/recover-password',
    },
    USERS: {
        ME: '/users/me',
        AVATAR: '/users/me/avatar',
        DELETE_REQUEST_OTP: '/users/me/delete-request-otp',
    },
    PROFILES: {
        ME: '/profiles/me',
    },
    BRANDING: {
        ME: '/branding/me',
    },
    PORTFOLIO: {
        ME: '/portfolio/me',
        CREATE: '/portfolio',
        UPLOAD: '/portfolio/upload',
        REORDER: '/portfolio/reorder',
        UPDATE: (id: string) => `/portfolio/${id}`,
        REPLACE_IMAGE: (id: string) => `/portfolio/${id}/replace-image`,
        DELETE: (id: string) => `/portfolio/${id}`,
        PUBLIC: (username: string) => `/portfolio/public/${username}`,
    },
    TRENDS: {
        CURRENT: '/trends/current',
        ARCHIVE: '/trends/archive',
    },
    FILTERS: {
        LIST: '/filters',
        SUGGEST_VARIABLES: '/filters/suggest-variables',
        VARIABLE_POOL_STATUS: '/filters/variable-pool-status',
        REPLENISH_VARIABLES: '/filters/replenish-variables',
    },
    UPLOAD: '/upload',
    JOBS: {
        GET: (id: string) => `/jobs/${id}`,
        LIST: '/jobs',
        RESULTS: '/jobs/results',
        GUEST: '/jobs/guest',
        BATCH: '/jobs/batch',
        DOWNLOAD: (id: string, variant: number, upscale?: boolean) => `/jobs/${id}/download?variant=${variant}${upscale ? '&upscale=1' : ''}`,
        PREPARE_HD: (id: string, variant: number) => `/jobs/${id}/prepare-hd?variant=${variant}`,
        REPLACE_RESULT: (id: string, variant: number) => `/jobs/${id}/replace-result?variant=${variant}`,
        DELETE: (id: string) => `/jobs/${id}`,
        BULK_DELETE: '/jobs/bulk',
        STATS: '/jobs/stats',
    },
    CREDITS: {
        BALANCE: '/credits/balance',
        PACKAGES: '/credits/packages',
        PURCHASE: '/credits/purchase',
        HISTORY: '/credits/history',
    },
    SUBSCRIPTIONS: {
        PLANS: '/subscriptions/plans',
        CURRENT: '/subscriptions/current',
        SUBSCRIBE: '/subscriptions/subscribe',
        CANCEL: '/subscriptions/cancel',
        REACTIVATE: '/subscriptions/reactivate',
    },
    REFERRALS: {
        STATS: '/referrals/my',
    },
    CAPTIONS: {
        GENERATE: (jobId: string) => `/captions/${jobId}`,
        GET: (jobId: string) => `/captions/${jobId}`,
    },
    SHOWCASE: {
        GET: (jobId: string) => `/showcase/${jobId}`,
        REVIEW: (jobId: string) => `/showcase/${jobId}/review`,
    },
    ADMIN: {
        USERS: '/admin/users',
        USER_IMAGES: (userId: string) => `/admin/users/${userId}/images`,
        STATS: '/admin/stats',
        FLUSH_DAILY_LIMITS: '/admin/flush-daily-limits',
        PORTFOLIOS: '/admin/portfolios',
        PORTFOLIO_ITEMS: (userId: string) => `/admin/portfolios/${userId}/items`,
        SMS_VERIFIED_COUNT: '/admin/sms/verified-count',
        SMS_SEND_BULK: '/admin/sms/send-bulk',
    },
    CHAT: {
        MESSAGE: '/chat/message',
    },
    DECORATIONS: {
        SUGGEST: '/decorations/suggest',
        POOL_STATUS: '/decorations/pool-status',
        REPLENISH: '/decorations/replenish',
    },
    MASTERS: {
        FEATURED: '/masters/featured',
        NICHE_COUNTS: '/masters/niche-counts',
        CATALOG: '/masters/catalog',
    },
    VERIFICATION: {
        STATE: '/verification/state',
        REQUEST: '/verification/request',
        UPLOAD_ID: '/verification/upload-id',
        UPLOAD_CERTIFICATE: '/verification/upload-certificate',
        UPLOAD_HYGIENE: '/verification/upload-hygiene',
        UPLOAD_QUALITY_PRODUCTS: '/verification/upload-quality-products',
        ADMIN_PENDING: '/verification/admin/pending',
        ADMIN_ALL: '/verification/admin/all',
        ADMIN_REVIEW: (userId: string) => `/verification/admin/${userId}/review`,
        ADMIN_BADGE: (userId: string) => `/verification/admin/${userId}/badge`,
        ADMIN_TIER: (userId: string) => `/verification/admin/${userId}/tier`,
        GLOW_STAR_STATE: '/verification/glow-star/state',
        GLOW_STAR_REQUEST: '/verification/glow-star/request',
        ADMIN_GLOW_STAR_LIST: '/verification/admin/glow-star',
        ADMIN_GLOW_STAR_REVIEW: (userId: string) => `/verification/admin/${userId}/glow-star`,
    },
    CATALOG: {
        SPECIALITIES: '/catalog/specialities',
        SERVICE_CATEGORIES: '/catalog/service-categories',
        DISTRICTS: '/catalog/districts',
        BRANDS: '/catalog/brands',
        STYLE_TAGS: '/catalog/style-tags',
    },
    NOTIFICATIONS: {
        REPORT: '/notifications/report',
    },
    REVIEWS: {
        CREATE: '/reviews',
        BY_MASTER: (masterId: string) => `/reviews/master/${masterId}`,
        MY_REVIEW: (masterId: string) => `/reviews/my/${masterId}`,
        UPDATE: (reviewId: string) => `/reviews/${reviewId}`,
        DELETE: (reviewId: string) => `/reviews/${reviewId}`,
    },
    ONBOARDING: {
        COMPLETE: '/onboarding/complete',
    },
    FAVORITES: {
        MASTERS: {
            LIST: '/favorites/masters',
            ADD: (masterProfileId: string) => `/favorites/masters/${masterProfileId}`,
            REMOVE: (masterProfileId: string) => `/favorites/masters/${masterProfileId}`,
        },
        PORTFOLIO: {
            LIST: '/favorites/portfolio',
            ADD: (portfolioItemId: string) => `/favorites/portfolio/${portfolioItemId}`,
            REMOVE: (portfolioItemId: string) => `/favorites/portfolio/${portfolioItemId}`,
        },
        STATUS: '/favorites/status',
    },
} as const;
