export const ROUTES = {
    HOME: '/',
    LOGIN: '/login',
    REGISTER: '/register',
    FORGOT_PASSWORD: '/forgot-password',
    CREATE: '/create',
    CREATE_RESULT: (jobId: string) => `/create/${jobId}` as const,
    DASHBOARD: '/dashboard',
    DASHBOARD_CREDITS: '/dashboard/credits',
    DASHBOARD_BRANDING: '/dashboard/branding',
    DASHBOARD_PROFILE: '/dashboard/profile',
    DASHBOARD_PORTFOLIO: '/dashboard/portfolio',
    DASHBOARD_REFERRALS: '/dashboard/referrals',
    SHOWCASE: (jobId: string) => `/showcase/${jobId}` as const,
    PORTFOLIO_PUBLIC: (username: string) => `/specialist/${username}` as const,
    MASTERS: '/masters',
    FACES: '/faces',
    FACE_DETAIL: (id: string) => `/faces/${id}` as const,
    FACES_JOIN: '/faces/join',
    DASHBOARD_MODEL: '/dashboard/model',
    WAITLIST_JOIN: (username: string) => `/w/${username}` as const,
    DASHBOARD_WAITLIST: '/dashboard/waitlist',
    DASHBOARD_BOOKINGS: '/dashboard/bookings',
    SEARCH: '/search',
    FAVORITES: '/favorites',
    APPOINTMENTS: '/appointments',
    MARKETPLACE: '/marketplace',
    MAP: '/map',
    BLOG: '/blog',
    VERIFY_PHONE: '/verify-phone',
    ONBOARDING: '/onboarding',
    ADMIN: '/admin',
    TERMS: '/terms',
    PRIVACY: '/privacy',
    REFUND: '/refund',
} as const;
