export const ROUTES = {
    HOME: '/',
    LOGIN: '/login',
    REGISTER: '/register',
    CREATE: '/create',
    CREATE_RESULT: (jobId: string) => `/create/${jobId}` as const,
    DASHBOARD: '/dashboard',
    DASHBOARD_CREDITS: '/dashboard/credits',
    DASHBOARD_BRANDING: '/dashboard/branding',
    DASHBOARD_PROFILE: '/dashboard/profile',
    DASHBOARD_PORTFOLIO: '/dashboard/portfolio',
    ONBOARDING: '/onboarding',
    DASHBOARD_REFERRALS: '/dashboard/referrals',
    SHOWCASE: (jobId: string) => `/showcase/${jobId}` as const,
    PORTFOLIO_PUBLIC: (username: string) => `/specialist/${username}` as const,
    ADMIN: '/admin',
} as const;
